
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;

public class Test {
    
    public static ArrayList<String> countries = new ArrayList<>(Arrays.asList(
   "Afghanistan",
   "Afrique du Sud",
   "Albanie",
   "Algérie",
   "Allemagne",
   "Andorre",
   "Angola",
   "Antigua-et-Barbuda",
   "Arabie Saoudite",
   "Argentine",
   "Arménie",
   "Australie",
   "Autriche",
   "Azerbaïdjan",
   "Bahamas",
   "Bahreïn",
   "Bangladesh",
   "Barbade",
   "Belgique",
   "Belize",
   "Bénin",
   "Bhoutan",
   "Biélorussie",
   "Birmanie",
   "Bolivie",
   "Bosnie-Herzégovine",
   "Botswana",
   "Brésil",
   "Brunei",
   "Bulgarie",
   "Burkina Faso",
   "Burundi",
   "Cambodge",
   "Cameroun",
   "Canada",
   "Cap-Vert",
   "République Centrafricaine",
   "Chili",
   "Chine",
   "Chypre",
   "Colombie",
   "Comores",
   "République du Congo",
   "République Démocratique du Congo",
   "Îles Cook",
   "Corée du Nord",
   "Corée du Sud",
   "Costa Rica",
   "Côte d'Ivoire",
   "Croatie",
   "Cuba",
   "Danemark",
   "République Dominicaine",
   "Djibouti",
   "Dominique",
   "Egypte",
   "Emirats Arabes Unis",
   "Equateur",
   "Erythrée",
   "Espagne",
   "Estonie",
   "Eswatini",
   "Etats-Unis",
   "Ethiopie",
   "Fidji",
   "Finlande",
   "France",
   "Gabon",
   "Gambie",
   "Géorgie",
   "Ghana",
   "Grèce",
   "Grenade",
   "Guatemala",
   "Guinée",
   "Guinée équatoriale",
   "Guinée-Bissau",
   "Guyana",
   "Haïti",
   "Honduras",
   "Hongrie",
   "Inde",
   "Indonésie",
   "Irak",
   "Iran",
   "Irlande",
   "Islande",
   "Israël",
   "Italie",
   "Jamaïque",
   "Japon",
   "Jordanie",
   "Kazakhstan",
   "Kenya",
   "Kirghizistan",
   "Kiribati",
   "Koweït",
   "Laos",
   "Lesotho",
   "Lettonie",
   "Liban",
   "Liberia",
   "Libye",
   "Liechtenstein",
   "Lituanie",
   "Luxembourg",
   "Macédoine du Nord",
   "Madagascar",
   "Malaisie",
   "Malawi",
   "Maldive",
   "Mali",
   "Malte",
   "Maroc",
   "Marshall",
   "Île Maurice",
   "Mauritanie",
   "Mexique",
   "Micronésie",
   "Moldavie",
   "Monaco",
   "Mongolie",
   "Monténégro",
   "Mozambique",
   "Namibie",
   "Nauru",
   "Népal",
   "Nicaragua",
   "Niger",
   "Nigeria",
   "Norvège",
   "Nouvelle-Zélande",
   "Oman",
   "Ouganda",
   "Ouzbékistan",
   "Pakistan",
   "Palaos",
   "Palestine",
   "Panama",
   "Papouasie-Nouvelle-Guinée",
   "Paraguay",
   "Pays-Bas",
   "Pérou",
   "Philippines",
   "Pologne",
   "Portugal",
   "Qatar",
   "Roumanie",
   "Royaume-Uni",
   "Russie",
   "Rwanda",
   "Saint-Christophe-et-Niévès",
   "Saint-Marin",
   "Saint-Vincent-et-les-Grenadines",
   "Sainte-Lucie",
   "Salomon",
   "Salvador",
   "Samoa",
   "São Tomé et Príncipe",
   "Sénégal",
   "Serbie",
   "Seychelles",
   "Sierra Leone",
   "Singapour",
   "Slovaquie",
   "Slovénie",
   "Somalie",
   "Soudan",
   "Soudan du Sud",
   "Sri Lanka",
   "Suède",
   "Suisse",
   "Suriname",
   "Syrie",
   "Tadjikistan",
   "Tanzanie",
   "Tchad",
   "République Tchèque",
   "Thaïlande",
   "Timor-Oriental",
   "Togo",
   "Tonga",
   "Trinité-et-Tobago",
   "Tunisie",
   "Turkménistan",
   "Turquie",
   "Tuvalu",
   "Ukraine",
   "Uruguay",
   "Vanuatu",
   "Vatican",
   "Venezuela",
   "Viêt Nam",
   "Yémen",
   "Zambie",
   "Zimbabwe"
    ));
    public static ArrayList<String> capitales = new ArrayList<>(Arrays.asList( 
    "Kaboul",
    "Bloemfontein/Le Cap/Pretoria",
    "Tirana",
    "Alger",
    "Berlin",
    "Andorre-la-Vieille",
    "Luanda",
    "Saint John's",
    "Riyad",
    "Buenos Aires",
    "Erevan",
    "Canberra",
    "Vienne",
    "Bakou",
    "Nassau",
    "Manama",
    "Dacca",
    "Bridgetown",
    "Bruxelles",
    "Belmopan",
    "Porto-Novo",
    "Thimphou",
    "Minsk",
    "Naypyidaw",
    "Sucre/La Paz",
    "Sarajevo",
    "Gaborone",
    "Brasilia",
    "Bandar Seri Begawan",
    "Sofia",
    "Ouagadougou",
    "Gitega",
    "Phnom Penh",
    "Yaoundé/Yaounde",
    "Ottawa",
    "Praia",
    "Bangui",
    "Santiago",
    "Pékin/Pekin",
    "Nicosie",
    "Bogota",
    "Moroni",
    "Brazzaville",
    "Kinshasa",
    "Avarua",
    "Pyongyang",
    "Séoul/Seoul",
    "San José/San Jose",
    "Yamoussoukro",
    "Zagreb",
    "La Havane",
    "Copenhague",
    "Djibouti",
    "Saint-Domingue",
    "Roseau",
    "Le Caire",
    "Abou Dabi",
    "Quito",
    "Asmara",
    "Madrid",
    "Tallinn",
    "Mbabane",
    "Washington D.C",
    "Addis-Abeba",
    "Suva",
    "Helsinki",
    "Paris",
    "Libreville",
    "Banjul",
    "Tbilissi",
    "Accra",
    "Athènes",
    "Saint-Georges",
    "Guatemala",
    "Conakry",
    "Bissau",
    "Malabo",
    "Georgetown",
    "Port-au-Prince",
    "Tegucigalpa",
    "Budapest",
    "New Delhi",
    "Jakarta",
    "Bagdad",
    "Téhéran/Teheran",
    "Dublin",
    "Reykjavik",
    "Jérusalem/Tel Aviv-Jaffa/Jerusalem",
    "Rome",
    "Kingston",
    "Tokyo",
    "Amman",
    "Nour-Soultan",
    "Nairobi",
    "Bichkek",
    "Tarawa-Sud",
    "Koweït/Koweit",
    "Vientiane",
    "Maseru",
    "Riga",
    "Beyrouth",
    "Monrovia",
    "Tripoli",
    "Vaduz",
    "Vilnius",
    "Luxembourg",
    "Skopje",
    "Antananarivo",
    "Putrajaya/Kuala Lumpur",
    "Lilongwe",
    "Malé/Male",
    "Bamako",
    "La Valette",
    "Rabat",
    "Delap-Uliga-Darrit/Majuro",
    "Port-Louis",
    "Nouakchott",
    "Mexico",
    "Palikir",
    "Chisinau",
    "Monaco",
    "Oulan-Bator",
    "Podgorica",
    "Maputo",
    "Windhoek",
    "Yaren",
    "Katmandou",
    "Managua",
    "Niamey",
    "Abuja",
    "Alofi",
    "Oslo",
    "Wellington",
    "Mascate",
    "Kampala",
    "Tachkent",
    "Melekeok",
    "Ramallah/Jérusalem-Est/Jerusalem",
    "Panama",
    "Port Moresby",
    "Asuncion",
    "Amsterdam",
    "Lima",
    "Manille",
    "Varsovie",
    "Lisbonne",
    "Doha",
    "Bucarest",
    "Londres",
    "Moscou",
    "Kigali",
    "Basseterre",
    "Sain-Marin",
    "Kingstown",
    "Castries",
    "Honiara",
    "San Salvador",
    "Apia",
    "São Tomé/Sao Tome/Sao Tomé",
    "Dakar",
    "Belgrade",
    "Victoria",
    "Freetown",
    "Singapour",
    "Bratislava",
    "Ljubljana",
    "Mogadiscio/Muqdisho",
    "Khartoum",
    "Djouba",
    "Colombo/Sri Jayawardenapura Kotte",
    "Stockholm",
    "Berne",
    "Paramaribo",
    "Damas",
    "Douchanbé/Douchanbe",
    "Dodoma",
    "N'Djaména/N'Djamena",
    "Prague",
    "Bangkok",
    "Dili",
    "Lomé",
    "Nuku'alofa",
    "Port-d'Espagne",
    "Tunis",
    "Achgabat",
    "Ankara",
    "Funafuti/Vaiaki",
    "Kiev",
    "Montevideo",
    "Port-Vila",
    "Cité du Vatican/Cite du Vatican",
    "Caracas",
    "Hanoï/Hanoi",
    "Sanaa",
    "Lusaka",
    "Harare"
    ));



    int choice;
    int nbquest;
    static Random random = new Random();



    public Test(int i, int j){ // type de question ( 0 on donne le pays/ 1 on donne la capitale)
                                // j = nombre de questions si all choisi alors rentrer 999
        this.choice = i;
        if(j!=999){
            this.nbquest = j;
        }
        else{
            this.nbquest = countries.size();
        }

    }

    public static int Random(){
        return (random.nextInt(countries.size()));
    }

    public static String RandomChoice(ArrayList quest, int i){
        String x;
        x= (String)quest.get(i);
/*         System.out.println(x);
        System.out.println( i ); */
        return x;
    }

    public static int series(ArrayList quest, ArrayList ans, int nbquest){
        int score = 0;
        Scanner scan = new Scanner(System.in); //La partie qui devra changer pour l'adaptation à l'interface
        String userAns;
        int cpt = 1;
        do {

                int r = Random();
                String aff = RandomChoice(quest, r); // Question affichée
                String answer = RandomChoice(ans , r); //La bonne réponse
                System.out.println( aff );
                userAns = scan.nextLine();
                    if(userAns == answer){ // Comparer les String caractère par caractère avec comparaison de tailles et accents. 
                        score = score +1;
                        System.out.println( "c'est bon" );

                    }
                    else{
                        score = score;
                        System.out.println( "C'est pas bon" );
                        //afficher la bonne réponse
                        

                    }
                    System.out.println( "Score: " + score );
                    System.out.println( "Question : "  + cpt );
                    System.out.println( "Bonne réponse :" + answer  +".");
                    System.out.println( "/" + userAns +"/" );
            cpt=cpt+1;

        }
        
        
        while(cpt <= nbquest) ;
        System.out.println( "Finis" );
        
//Ajouter test pays pas déjà fait !  Pour ca, à chaque tour ajouter le pays fait dans une liste et comparer tous les éléments de cette liste au pays random donné
//Si déjà présent alors faire un autre random sinon, poser la question et l'ajouter
        return score;
    }

    //Pour pays à plusieurs choix séparer les choix par des / et le prendre en compte lors de la lecture de la réponse
    // Lire jusqu'à / et recommencer jusqu'à fin de la case i 
}



